name: Calculator2
on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'Input for Number 1'
        required: true
        type: number
      number2:
        description: 'Input for Number 2'
        required: true
        type: number
      operation:
        description: 'Choose the operation to perform'
        type: choice
        required: true
        options:
          - '+'
          - '-'
          - '/'
          - '*'
jobs:
  calculation:
    runs-on: windows-latest
    outputs:
      result: ${{ steps.result-output.outputs.result }}
    steps:
      -  run: |
          $result = ${{ inputs.number1 }}${{ inputs.operation }}${{ inputs.number2 }}
          echo result=$result >> $env:GITHUB_OUTPUT
         id: result-output
  display-result:
    needs: calculation
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Your result is ${{ needs.calculation.outputs.result }}'