name: Calculator
on:
  workflow-dispatch:
    inputs:
      number1:
        description: 'Input for Number 1'
        required: true
        type: number
      number2:
        description: 'Input for Number 2'
        required: true
        type: number
      operation:
        description: 'Choose the operation to perform'
        type: choice
        required: true
        options:
          - '+'
          - '-'
          - '/'
          - '*'
jobs:
  calculation:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.operation == '+'
        run: echo ${{ inputs.number1 }}+${{ inputs.number2 }}
      - if: inputs.operation == '-'
        run: echo ${{ inputs.number1 }}-${{ inputs.number2 }}
      - if: inputs.operation == '/'
        run: echo ${{ inputs.number1 }}/${{ inputs.number2 }}
      - if: inputs.operation == '*'
        run: echo ${{ inputs.number1 }}*${{ inputs.number2 }}