name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  labels:
    types:
      - created
jobs:
  calculation:
    runs-on: windows-latest
    steps:
      -  run: echo ${{ toJSON(github.event) }}