name: Testing Composite Actions
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/cache-dpe
        with:
          name: 'Devansh Popli'
          age: 24