name: Matrix workflow
on: push
jobs:
  Build:
    strategy:
      matrix:
        operating-system: ["ubuntu-latest","windows-latest"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - run: echo "In build job"