name: Matrix workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: Write-Host 'this is step 1'
      - name: step 2
        run: echo 'this is step 2'
      - name: step 3
        if: failure()
        run: echo 'this is step 3 on failure'