name: Matrix workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.action }} 
      - run: echo ${{ github.action_path }}
      - run: echo ${{ github.job }}