name: Workflow Example
run-name: ${{ github.actor }} has created this workflow!
on:
  push:
    branches:
      - main
    branches-ignore:
      - dev
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
