name: Workflow Example
run-name: ${{ github.actor }} has created this workflow!
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}
