name: Matrix workflow
on: push
env: 
  NAME: Devansh Popli
jobs:
  Build:
    env:
      NAME: Build-Name
    runs-on: windows-latest
    steps:
      - run: echo $RUNNER_NAME $RUNNER_OS $RUNNER_TEMP $RUNNER_TOOL_CACHE