name: Matrix workflow
on: push
env: 
  NAME: Devansh Popli
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(runner) }}' 
      - run: echo ${{ runner.name }} ${{ runner.os }} ${{ runner.temp }} ${{ runner.arch }}  ${{ runner.tool_cache }}
      - run: |
          mkdir ${{ runner.temp }}/new_folder
          cd ${{ runner.temp }}
          ls