name: Permissions Workflow
on: 
  push:
    branches:
      - main
jobs:
  Build:
    permissions:
      read: none
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      