name: Artifacts Workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/upload-artifact@v1
        with:
          name: Build Artifacts
          path: index.html
      - uses: actions/upload-artifact@v1
        with:
          name: Test Artifacts
          path: src/test