name: Environment Workflow
on:
  push:
    branches:
      - main
env:
  NAME: Devansh
jobs:
  job1:
    if: ${{ env.NAME }} == 'Devansh'
    name: My_Job
    runs-on: ubuntu-latest
    steps:
      - run: echo $NAME