name: Functions
on:
  push:
    branches:
      - main
      - dev
      - feature
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ join(github.event.push.branches.*.name) }}
