name: Workflow Commands
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::error::This is a custom error by Devansh'
      - run: echo '::debug::This is a debug message'