name: Matrix Workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        version: [10,12,14]
        exclude:
          - os: ubuntu-latest
            version: 12
    steps:
      - name: Code Checkout
        uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.versions }}
